
; generated by PrusaSlicer 2.9.2 on 2025-07-13 at 09:07:16 UTC


;
; thumbnail_QOI begin 16x16 644
; cW9pZgAAABAAAAAQBAD+W1tbylXCCsP+al1Q/pZiLTQKwDvDsIgKwjT+s2UX/tFpABw7wwr+fn5+pI
; gKwRw1/qBQAP6wWAD+pGMiO8KqiP6KioqIiIuICjQc/sVjACX+cDgA/p5PADU7wbyIsoj+ZWVlO1X+
; YFhQ/sJnC5aX/nw+AB2kH/59RAv+0WkA/odgOP5fX1/+iYmJkIgGLDvA/n1kSv6IRAAdwKQf/l1WT/
; 5sUjj+v2AA/qxrKf6Li4srCiw7wf6GbVT+ez4A/m49DP5lSS07wP5iWVD+pFIA/tFpAP5hYWEswH/+
; aVxPC/56WTg9/nVPKf6PgXP+bGxsO6yI/oqKiv6hWA41/mhbTjsl/pVhLTP+oFAA/mhFIjvApoj+j4
; +PrIiLiBH+d0wh/shkAP6HYDj+aVxP/rNlFjMfHTQ7wKmI/o6OjlWziP5paWkb/rZbAKyHM/6gUAAd
; wKQf/lxVTju3iDj+aGhok4gv/piYmIOI/qRSADP+iEQA/nA4AMD+ZEgsLMD+hISEmIiEiCzBo4gT/o
; pPEx3ANT0swQkKLH/BLDv+fVMoHacf/l1WTyzEO8Ms/mVUQ/5nSy/+jIyMQDsswjvCLMMKuIj+mpqa
; /mdnZyzAAAAAAAAAAAE=
; thumbnail_QOI end
;
; Z_POS_DWELL.gcode for Core One (Z-bed positioning)
; Generated for OTTOMAT3D automation - moves Z to 200mm and dwells

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

M73 P0 R0
M73 Q0 S0
M201 X10000 Y10000 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X350 Y350 Z12 E100 ; sets maximum feedrates, mm / sec
M204 P7000 R2500 T7000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

M486 S0
M486 AEmbossed text
M486 S-1

;TYPE:Custom
M17 ; enable steppers
M862.1 P0.4 A0 F1 ; nozzle check
M862.3 P "COREONE" ; printer model check
M862.5 P2 ; g-code level check
M862.6 P"Input shaper" ; FW feature check
M115 U6.3.3+10442

M555 X119.517 Y83.7025 W32 H7.50098

G90 ; use absolute coordinates
M83 ; extruder relative mode

G1 Z200 F2400 ; move Z to 200mm for ejection

M84 S600 X Y E ; turn off X Y E motors, keep Z active

G4 S3600 ; dwell for 1 hour (3600 seconds)

;PAUSE_PRINT
M117 WAITING FOR EJECTION
; M601

; Core One Z-positioning for OttoEject automation
; estimated printing time = 1h 0m 10sick up the phone